### ISSUE TITLE
Sticky fields

### ISSUE THREAD

**Issue by qwiglydee** [1nsp1r3rnzt/chrome-anki-quick-adder#13]
Anki has sticky fields which are kept across several card being added in serial. This is indeed a use case for chrome-adder, and it should keep such fields.

Perhaps it makes sense to keep all fields, if there's a button to clear some or all of them.

**Comment by 1nsp1r3rnzt** [comment]
Did you mean frozen fields? Yes, having sticky fields is indeed useful.I will create a button similar to sticky fields in Anki.

**Comment by 1nsp1r3rnzt** [comment]
Added sticky fields  settings. Each field has an icon to make it sticky. The data is persisted after adding new note to add more serial in serial mode.
